version: '3'
services:
  app:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/yourDatabaseName
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
